API Key:
  openai: "sk-eUXrnuOoH3cZQwVyD21b886e583745F09e2b95AaD7C611D3"
  deepseek: "sk-7f3baf18d09f4d928ffb28a89358cabd"
  tmdb: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkYTJlNjg1MTE2Y2ZhYjdiODMyNGExOTY4NmU3NWM3MiIsIm5iZiI6MTc2NTI2MjcwMS4yNDg5OTk4LCJzdWIiOiI2OTM3YzU2ZDAyNmIyNjk2YzNlYjFhOTMiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.wLY9hDOISSo-ZOeBCKQ9PqhYMp3li7K_KUb7QXu7sPA"
  spotipy_client_id: "bc88980f1ff841f2b47aac85ce88f61a"
  spotipy_access_token: "BQBBT3rrS8Tl2vpZDzo12gk62WuLybxWMlKlPe-2qUpeyW_ill_-nHsq8zLzWxkrde8DM0lK4_ImR8sm5Lr_Q1RK2q5Sg_kvbalux4WUw6iBZOl52-9LBfztihERL4RodfXaKU6S2tVh6eIIScrjVjUd5ZT95i_8QijwKJr5kKPfM2DZoQnmRxloZOQ7N9bjrRz6lhHdU51k2NpdW2tWLQKyFH_auk4iwvPRhdqDO0KRuUrGeHOOwc8UxA1yOy4xQ2Tly3WPVG5xY3fyjnzGM9Ff2VoHQk7cjPLYigrlVKu5AQAI90M_22VHOETBcfVG6YCbBd9gliIhOwWXYUMA6qn0b2zxd4Wty4aCN0-oJkl_2VtBexTBfTpjqgjXQ55MKn-ExtxLUdixWDA"
  spotipy_redirect_uri: "http://127.0.0.1:8000/callback"
  lastfm: "d214ed9df84f601f4bf300a9396f38d1"
  base_url: "https://api.rcouyi.com/v1"